### ISSUE TITLE
WordPress WooCommerce intergration

### ISSUE THREAD

**Issue by G-Driver** [inoerp/inoERP#10]
Is there any chance to get InoERP work with Woocommerce ?

**Comment by inoerp** [comment]
There is no reason why you can’t integrate. But sorry to say, it’s not in our current plan/future enhancement list. 
Just to inform you, we are about release a full-fledged e-Commerce module that integrates with POS, Sales, Price List, Delivery, Inventory, AR & GL.

**Comment by G-Driver** [comment]
Sounds good about the next releases, but to bad there won't be a intergration with Woocommerce.

Another question, can I help you guys with the translation to Dutch and Croatian?

**Comment by inoerp** [comment]
Yes, that would be of great help.

We have some translation in German but that’s a dictionary conversion. It would be nice if you can help in that. Please note that we are still in version 0.1.2 and plan to release version 0.2 by mid of April. The version 1 is not going to be released very Soon. (Though, the current version is quite stable and ready for production usage)

Regarding Woocommerce,  We are always open for ideas. So, I am not saying we won’t do any third-party integration. Currently, it’s not in our list.  Our e-commerce is more in line with Oracle i-Store

**Comment by G-Driver** [comment]
Ok, so do you work with .po / .mo language files like WordPress or some other method?

**Comment by inoerp** [comment]
Yes, that's correct. We use gettext.

**Comment by G-Driver** [comment]
So where can I find the english translation file?

**Comment by inoerp** [comment]
You can get it from

https://github.com/inoerp/inoERP/blob/master/inoerp/locale/en_US/LC_MESSAGES/messages.po
I think it covers 80-85% + of all the terms but few success/error messages (long sentences) are not yet available for translation. 

As I have mentioned earlier, the development is currently in full swing; and by the time, you complete all the translation we would have released few more modules/extensions.
