### ISSUE TITLE
curly bracket error

### ISSUE THREAD

**Issue by Deathkon** [inoerp/inoERP#115]
Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\xampp\htdocs\inoerp\inoerp_server\includes\functions\functions.inc on line 2119

**Comment by ajaybehera53** [comment]
Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\xampp\htdocs\inoerp\includes\functions\functions.inc on line 2039

**Comment by borgy65** [comment]
I think this ERP is dead. You'll get that error because you have a higher version of PHP. Try to downgrade it to at least PHP 7.

**Comment by inoerp** [comment]
The product is in the process of migration to Go and Dart (Go for backend and Flutter for frontend). The PHP version is not maintained. You can migrate to the new version if you want to continue to use inoERP. 
Read the documentation @ [docs.inoerp.com](http://docs.inoerp.com/)
