### ISSUE TITLE
Cannot show search Org data

### ISSUE THREAD

**Issue by techcare2u** [inoerp/inoERP#12]
I have downloaded the latest version of inoerp and install to my virtualbox. Installation done successfully but I can't search any org data "Org->Search Org". I have checked  Mysql and there are some records inside. I am login using inoerp . 

![inoerp_org_search](https://cloud.githubusercontent.com/assets/10739626/8058245/b9166c16-0eea-11e5-8ce6-33091db5fcfd.jpg)

**Comment by inoerp** [comment]
Check below forum topics

http://inoideas.org/content.php?mode=2&content_id=458&content_type_id=1

http://inoideas.org/content.php?pageno=2&&mode=2&content_id=273&content_type_id=1

Most probably you dont have organization access!!

**Comment by techcare2u** [comment]
yeah..is the organization access..need to add "Admin->role access->group access" select user group code and press the small refresh button  beside then add all the org..
Thank you..

**Comment by inoerp** [comment]
Yes that's correct.
Did that work for you!!!
