### ISSUE TITLE
Nginx Integration

### ISSUE THREAD

**Issue by jhnferraris** [inoerp/inoERP#13]
Can this be integrated in Nginx? Can we also have a full documentation how to do the manual installation in nginx? The manual installation flow is quite vague in my own level of understanding.

**Comment by inoerp** [comment]
We used to test in Nginx but have stopped as none of our customers are using it.
We test only in 2 servers - IIS & Apache.

I know documentation is not good enough as it has not been updated for quite some time but our forum is quite active. You can ask all your questions/issues over there

**Comment by inoerp** [comment]
Tried  the latest version on nginx with php 5.5 and MaridaDB...Worked fine w/o any issue

**Comment by jhnferraris** [comment]
@inoerp Can you comment the the workflow? thanks!

**Comment by inoerp** [comment]
Sorry didnt get you...what workflow your are referring to ?

**Comment by jhnferraris** [comment]
@inoerp The workflow on setting up the site to nginx.

**Comment by inoerp** [comment]
You use apache/iis/nginx that's quite irrelevant for installation and  setup.
The installation and setup is same for all.

**Comment by jhnferraris** [comment]
Got it to work. Thanks!
