### ISSUE TITLE
SQL-query error

### ISSUE THREAD

**Issue by dutchpatriot** [inoerp/inoERP#17]
Hi,

In the file inoerp.sql i keep getting errors...

On 3 different servers...

SQL-query:

CREATE TABLE IF NOT EXISTS `prj_role` (
  `prj_role_id` int(12) unsigned NOT NULL AUTO_INCREMENT,
  `role_name` varchar(25) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `user_role` varchar(25) DEFAULT NULL,
  `effective_from` date DEFAULT NULL,
  `effective_to` date DEFAULT NULL,
  `labor_cost_cb` tinyint(1) DEFAULT NULL,
  `contract_member_cb` tinyint(1) DEFAULT NULL,
  `project_member_cb` tinyint(1) DEFAULT NULL,
  `task_member_cb` tinyint(1) DEFAULT NULL,
  `scheduling_cb` tinyint(1) DEFAULT NULL,
  `min_job_level` int(4) DEFAULT NULL,
  `max_job_level` int(4) DEFAULT NULL,
  `hr_job_id` int(12) DEFAULT NULL,
  `created_by` int(12) NOT NULL,
  `creation_date` datetime(1) DEFAULT NULL,
  `last_update_by` int(12) NOT NULL,
  `last_update_date` datetime DEFAULT NULL,
  PRIMARY KEY (`prj_role_id`),
  UNIQUE KEY `value_group` (`role_name`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4
MySQL meldt: Documentatie

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1) DEFAULT NULL,
  `last_update_by` int(12) NOT NULL,
  `last_update_date` date' at line 17

**Comment by ryo7689** [comment]
use editor to modify the sql file change the part " creation_date datetime(1) DEFAULT NULL" to "creation_date datetime DEFAULT NULL"

**Comment by vutranngocthanh** [comment]
CREATE ALGORITHM = UNDEFINED DEFINER =  `root`@`localhost` SQL SECURITY DEFINER VIEW  `ap_import_claim_v` AS SELECT `eh`.`claim_number` AS  `claim_number` ,  `eh`.`hr_expense_header_id` AS  `hr_expense_header_id` ,  `eh`.`bu_org_id` AS  `bu_org_id` , `eh`.`hr_employee_id` AS  `hr_employee_id` ,  `eh`.`claim_date` AS  `claim_date` ,  `eh`.`status` AS  `status` ,  `eh`.`purpose` AS `purpose` ,  `eh`.`doc_currency` AS  `doc_currency` ,  `eh`.`department_id` AS  `department_id` ,  `eh`.`reason` AS  `reason` , `eh`.`currency` AS  `currency` ,  `eh`.`exchange_rate_type` AS  `exchange_rate_type` ,  `eh`.`exchange_rate` AS  `exchange_rate` , `eh`.`header_amount` AS  `header_amount` ,  `user`.`supplier_id` AS  `supplier_id` ,  `he`.`first_name` AS  `first_name` ,  `he`.`last_name` AS  `last_name` ,  `he`.`identification_id` AS  `identification_id` 
FROM (

(
`hr_expense_header`  `eh` 
JOIN  `user`
)
JOIN  `hr_employee`  `he`
)
WHERE (
(
`eh`.`status` =  'APPROVED'
)
AND (
`user`.`hr_employee_id` =  `eh`.`hr_employee_id`
)
AND (
`he`.`hr_employee_id` =  `eh`.`hr_employee_id`
)
);

MySQL a répondu: Documentation

#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation

**Comment by vutranngocthanh** [comment]
plase help me error when i import data

**Comment by inoerp** [comment]
Use root user
if you dont have access then open the inoerp.sql file and remove DEFINER =
root@localhost (ctrl find replace with blank)
ELse wait for sometime. I will do that in github
