### ISSUE TITLE
Unable to save new record and update existing record.  

### ISSUE THREAD

**Issue by premnacre** [inoerp/inoERP#18]
What should be the process to handle this issue.
below is the message shows at record saving tme.

Save failed!! error@inosavel line 254
DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
Transaction complete 3

**Comment by premnacre** [comment]
Finally i got solution. My PHP default timezone is not saved with UTC. now its working fine.

**Comment by inoerp** [comment]
ok..good!
