### ISSUE TITLE
Approvals not working

### ISSUE THREAD

**Issue by kchizi** [inoerp/inoERP#24]
Approvals seem not to be working in all modules, i have created approval limits and configured purchasing control for supervisor

In HR supervisor is not getting saved, also employee associations to user do not update in DB

**Comment by inoerp** [comment]
What do you mean by approval not working?
The system not sending any approval notification? 
I Just checked for PO and Expense claim, and both are working

Please attach all your setup and transaction screenshots

**Comment by kchizi** [comment]
The setup for PO ![purchasing control inoerp](https://cloud.githubusercontent.com/assets/669267/15856280/2e91e740-2cbd-11e6-90e3-99c308cdd519.png)

**Comment by inoerp** [comment]
Even of that, you need to do the approval setups in HR module.
Assign role to the employee/buyer
Create Approval Limit
Assign Approval Limit to the role.

Makes sure the supervisor has a role that has enough privileges to approve
the PO

**Comment by kchizi** [comment]
Thank you, i have changed to hierarchy and assigned approval limits, PO approval has worked, the notifications are not sent yet, is there special configuration for this?

**Comment by inoerp** [comment]
Notification will be only sent if the buyer ( a  person who is approving the PO) does not have enough approval limit. If the buyer has enough approval limit, then system will approve the PO and won't send any notification

**Comment by kchizi** [comment]
thank you.

**Comment by Incredible12** [comment]
Where to assign position hierarchy name

**Comment by Incredible12** [comment]
I dont find where to assign position hierarchy name against  the operating unit
