### ISSUE TITLE
Warning: First parameter must either be an object or the name of an existing class in C:\xampp\htdocs\inoERP-master\inoerp\modules\sys\profile\class_sys_profile_line.inc on line 66

### ISSUE THREAD

**Issue by Ekodeswa1223** [inoerp/inoERP#27]
Warning: First parameter must either be an object or the name of an existing class in C:\xampp\htdocs\inoERP-master\inoerp\modules\sys\profile\class_sys_profile_line.inc on line 66

Warning: First parameter must either be an object or the name of an existing class in C:\xampp\htdocs\inoERP-master\inoerp\modules\sys\profile\class_sys_profile_line.inc on line 72

**Comment by inoerp** [comment]
If you are looking for a fix then provide the details such as where you are  getting this message, what is your OS, etc . Please attach screenshots if possible.

Refrain from creating an issue without providing details. If you don't have the time to write details. No body will care to read it.

**Comment by Ekodeswa1223** [comment]
another question, 
1. how to modify the home page, its can combine with wordpress plugin for page builder?
2. i want to make the modules its more scope by HRD, FINANCE department , etc.
how to edit ?

**Comment by inoerp** [comment]
Use the forum @ inoideas.org for such generic questions
