### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by wahono77** [inoerp/inoERP#3]
I try install InoERP, but I got error message : 
Notice: Undefined property: stdClass::$phone_no in C:\UniServer\www\inoerp\extensions\site_info\class_site_info.inc on line 116

Fatal error: Can't use function return value in write context in C:\UniServer\www\inoerp\modules\inv\locator\class_locator.inc on line 171

What's wrong in my step?

Thanks

**Comment by inoerp** [comment]
Seems Like you are using an old data base file.

Can you get the latest database file and put it in below directory inoerp.sql
inoerp\engine\install\inoerp.sql

**Comment by inoerp** [comment]
Seems Like you are using an old data base file

Can you get the latest database file  located @

https://github.com/inoerp/inoERP/tree/master/inoerp/engine/install

and put it in below directory inoerp.sql
inoerp\engine\install\inoerp.sql


and then try again

**Comment by wahono77** [comment]
I've download the new sql file, but when I go to localhost/inoerp I got the same error message.

Should I install manually?

**Comment by inoerp** [comment]
Are you using the released version 0.1.2 
or the current version from Master. If you are using current version from master I would suggest you to delete all files and download a new copy

Yes, you can try manual installation if you know how to import db file through phpmyadmin or through other means.

If nothing works the comment out everything from C:\UniServer\www\inoerp\extensions\site_info\class_site_info.inc after the class definition .i.e from line 110 to the end.
Then try to install and remove the comments.

If you use skype then can add and contact.inoerp. I can guide you through the installtion

**Comment by wahono77** [comment]
I use PHP Version 5.4.19, maybe it from PHP version?

**Comment by inoerp** [comment]
Sorry...you need 5.5 +

**Comment by wahono77** [comment]
Soryy, I'll try to upgrade

**Comment by wahono77** [comment]
After upgrading PHP 5.6, it's normally. thanks

**Comment by inoerp** [comment]
Good.
Thanks for the confirmation. I am closing this ticket
