### ISSUE TITLE
After Successful Installation,Going to homepad i got below mention error.

### ISSUE THREAD

**Issue by deepesh08** [inoerp/inoERP#32]
Notice: Undefined property: stdClass::$content_color in C:\xampp\htdocs\inoerp\extensions\site_info\class_site_info.inc on line 134

**Comment by inoerp** [comment]
Database version and corresponding class definition are not in sync in the development version.
Either use a released version or get the latest the developed code from github after 48 hours

**Comment by shelkesantosh** [comment]
Notice: Undefined property: stdClass::$ar_revenue_schedule_cb in C:\wamp\www\inoerp\extensions\site_info\class_site_info.inc on line 142

**Comment by inoerp** [comment]
Issue has been resolved in the latest release
