### ISSUE TITLE
user search failed.

### ISSUE THREAD

**Issue by zhuxingang** [inoerp/inoERP#36]
I installed inoERP on my local host. And I register a new user "scott", then I log in as admin. From Admin->User->"Search Users", I input "scott" in Username field, then press Search button. But I got a prompt "Search Failed". 
I should see the use "scott", but Failed. Why?

**Comment by zhuxingang** [comment]
Someone said I should use "inoerp" user, however, "inoerp" user didn't work either.

**Comment by zhuxingang** [comment]
I changed the owner of inoerp directory to apache, and change the selinux role to ttpd_sys_rw_content_t. It works.

 I think the reason is Selinux is enable.

**Comment by designerxxx** [comment]
I don't understand what you did.
