### ISSUE TITLE
0.4.1 Fatal error: Cannot redeclare __() (previously declared in C:\...\locale\gettext.inc:286)

### ISSUE THREAD

**Issue by ReactorShop** [inoerp/inoERP#39]
I'm getting this error during installation:

`( ! ) Fatal error: Cannot redeclare __() (previously declared in C:\vhosts\Sistemas-Ino1\locale\gettext.inc:286) in C:\...\locale\gettext.inc on line 501
Call Stack
#	Time	Memory	Function	Location
1	0.0030	371224	{main}( )	...\install.php:0
2	0.0804	503800	include_once( 'C:\...\includes\basics\basics.inc' )	...\install.php:13
3	2.2916	7910568	require_once( 'C:\...\locale\gettext.inc' )	...\basics.inc:450
`

It's fixed by changing gettext.inc at line 501 from this:
`function __($msgid) {
        return ___($msgid);
    }` 

To this:
`if (!function_exists('__')) {
    function __($msgid) {
        return ___($msgid);
    }
    }`

**Comment by erotundo** [comment]
I have the same error and installation it's not possible

**Comment by ReactorShop** [comment]
@erotundo, 0.5.1 no longer shows this error, so I'd suggest for you to download it from https://sourceforge.net/projects/inoerp/ and install again.

This issue will be closed because it's already solved in 0.5.1
