### ISSUE TITLE
Fatal Error on install

### ISSUE THREAD

**Issue by piercarlo62** [inoerp/inoERP#45]
I have following warning before installation:

Warning: set_time_limit() has been disabled for security reasons in /home/vol11_4/byethost11.com/b11_18957543/inoerp.byethost11.com/htdocs/install.php on line 6

And I retrieve following error during install:

Fatal error: Maximum execution time of 20 seconds exceeded in /home/vol11_4/byethost11.com/b11_18957543/inoerp.byethost11.com/htdocs/engine/install/steps/complete_install.php on line 42.

And as I have not permission to modify php.ini to give change default time with  set_time_limit(), that is set in 20 second.

Can I solve in some way ?

Thank you in advance

Piercarlo

**Comment by inoerp** [comment]
You need to enable it for installation (& maybe after that depending on your business volume).
There are many programs such as MRP calculation might need more than 5-10 mins to complete depending on your business volume.
