### ISSUE TITLE
One payment term doesn't match its description

### ISSUE THREAD

**Issue by ReactorShop** [inoerp/inoERP#51]
@inoerp, I don't know which payment term was considered here (please check the red circled one):

![image](https://cloud.githubusercontent.com/assets/5473636/19979959/862aa7dc-a1b9-11e6-96fd-3b1b2c3c221d.png)

I think this is something you may need to check on your sql files.

**Comment by inoerp** [comment]
You can modify the description. The inbuilt payment terms are only for reference not for actual production usage
