### ISSUE TITLE
Purchase Curreny

### ISSUE THREAD

**Issue by avancer2** [inoerp/inoERP#52]
![error_currency](https://cloud.githubusercontent.com/assets/23697476/20558762/a7970350-b197-11e6-9049-c76d805118f1.png)

While creating the Purchase Order I am getting error on Currency. I have entered Doc Currency and Ledger Currencly. Stil i am getting currency error. For support i am attaching the Screen short for same.

**Comment by inoerp** [comment]
Is not the error message obvious ?
It clearly states that supplier site is missing. So, select a supplier site in basic info tab

**Comment by avancer2** [comment]
Sorry sir for wrongly share the screen short. I am attaching the right error screen short " Currency Error"
![currency_eror](https://cloud.githubusercontent.com/assets/23697476/20614874/aab6df52-b2f9-11e6-986c-7bc56286c5d6.png)
