### ISSUE TITLE
role access

### ISSUE THREAD

**Issue by Sriram1234567** [inoerp/inoERP#53]
basic role user able to update the all users address.please find the attachment
![1479982243_untitled1](https://cloud.githubusercontent.com/assets/23730901/20612293/6b9f9f22-b2de-11e6-854e-ffba3a20e396.png)

**Comment by Sriram1234567** [comment]
user can see there address only not all user address

**Comment by inoerp** [comment]
In the current version, a view only a user can see both the view and update button. However, the user with view-only access can't update any address. The fix will be applied in tomorrow's commit.

Regarding the second part of your question. If you give view access, then the user will be able to view all addresses.
If you don't want the user to view all addresses then remove the object from the role
