### ISSUE TITLE
Purchasing Transaction - Receipt/Return  error

### ISSUE THREAD

**Issue by kartheesanavancer** [inoerp/inoERP#56]
![screenshot_7](https://cloud.githubusercontent.com/assets/22850997/20657629/6536dbf6-b55d-11e6-9ad7-e239005c2917.png)

Hi,
  In Purchasing Transaction i create invoice it showing Record couldnt be saved. Error @ trait_dbObject_t.inc @@line730
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'inv_intorg_transfer_line_id' in 'field list'
Transaction complete

**Comment by inoerp** [comment]
Your DB and Class files are not in sync.
Update your installation or do a new one

**Comment by kartheesanavancer** [comment]
![screenshot_8](https://cloud.githubusercontent.com/assets/22850997/20667055/6d553f5a-b58d-11e6-9bcf-b16fc0c12b37.png)
Hi sir,
In Adding Purchasing Transaction - Receipt/Return its showing PO Received Quantity is SuccessfullyUpdated
The item is not enabled for Inventory Transaction
Frozen cost is not available for the entered item id 3

INV Transaction Lines are Successfully Created
Transaction complete
3
this kind of msg. data will be store in  inv_receipt_header table only ,its not store in inv_receipt_line

**Comment by inoerp** [comment]
Is not the message self-explanatory: you don't have frozen cost for an asset item. Either make the item as an expense or create a frozen cost for the item.

Please don't create an issue for this kind of problems. Read the documentation or ask for help in the forum. This is not an issue with the product.

**Comment by kartheesanavancer** [comment]
Send me the full documentation of inoerp, or  documentation link sir,
