### ISSUE TITLE
HR Payroll Line Details Not working

### ISSUE THREAD

**Issue by kartheesanavancer** [inoerp/inoERP#59]
![screenshot_1](https://cloud.githubusercontent.com/assets/22850997/21048398/18f12658-be35-11e6-901c-f489b1e6fb27.png)

I am adding payroll data, it's not adding status, period name,and description.

**Comment by inoerp** [comment]
That's the standard feature. You can't update the line details as those are system generated data.
If you have difficulty in understanding a specific functionality, then use the forum. Don't raise an issue
