### ISSUE TITLE
How to add organization and users

### ISSUE THREAD

**Issue by jony1982** [inoerp/inoERP#6]
Hello ,

I went through the video of InoERP and its really good, 
but we are unable to add the new organizations and users for that organization 
Please help us.
Thank You

**Comment by inoerp** [comment]
To create a new organization, navigate to Setup -> Org -> Generic Organization
You can search existing org in Setup -> Org -> Search Orgs
and then check the existing org setup before creating any new org.

Each type of org (Business Org, Enterprise Org , Legal & inventory Org) has different usages and setups can be configured after generic organization is created.

Users can be created by navigating to Admin -> User .

After creating user, you can assign role by navigating to Admin -> Role Access

**Comment by jony1982** [comment]
Hello ,
Thank you for your valuable reply,
I need to know can we use the inoERP for multiple organizations, i mean Super Admin will create the organization and also create an admin for that organization and remaining like add users for particular that organization will be on that organization admin. Is it possible ?. 
Please reply me if you didnt understand my requirement.
Thank You

**Comment by inoerp** [comment]
Hi,

This is a generic business requirements questions and others might have similar question. So, I have posted a topic in out forum with my ans. You can read it @
[Forum Topic](http://inoideas.org/content.php?mode=2&content_id=273&content_type=forum)

Thanks,
Nd
