### ISSUE TITLE
Payroll not working 

### ISSUE THREAD

**Issue by kartheesanavancer** [inoerp/inoERP#60]
In payroll data are not adding,
![screenshot_1](https://cloud.githubusercontent.com/assets/22850997/21080802/8bea7d26-bfde-11e6-83b7-e20981c8cd6b.png)

This issue not fixing...Your demo server also not working...

**Comment by inoerp** [comment]
Tested again and there is nothing wrong.
As I have mentioned earlier, use the forum if you have any problem.
Don't raise an issue in Github if it;s not an issue

![image](https://cloud.githubusercontent.com/assets/6542612/21081271/cbb24908-bfba-11e6-9e1a-cdfd2cbb6b57.png)
