### ISSUE TITLE
HR Employee Birthdate

### ISSUE THREAD

**Issue by johnestep** [inoerp/inoERP#61]
Can only select 2016 and forward til 2020

Need to be able to select backwards

**Comment by inoerp** [comment]
Employe birth date can be entered in several different ways in different forms.
Can you provide more details: which field & form you are referring to (navigation, template name, etc)
Attach a screenshot

**Comment by johnestep** [comment]
When you go to edit an employee birthday and click on the year, the only years available are 2016-2020

It should allow dates going back MANY years ;)

Hope that explains the issue. If not I can get you a screenshot later

**Comment by inoerp** [comment]
Checked again, there is nothing wrong. You might be using the custom template. 
Go to themes -> default -> template and delete the hr_employee_template.php file.

**Comment by johnestep** [comment]
I just unzipped and started using it, is the default to use a custom template?

**Comment by inoerp** [comment]
Yes, one custom template is provided as sample example. So, that developer can create more custom templates as required for other modules.
Now, don't raise an issue if you are unsure if it's a real issue or not. 300+ people get notified for each message. Use the forum for such generic questions
