### ISSUE TITLE
attachment for individual

### ISSUE THREAD

**Issue by Sriram1234567** [inoerp/inoERP#62]
Hi

In inoERP attatchments are displaying at same location due to that am unable to find files clearly which file is for what. So 
I want attachments individually like tab1 having 1 attachment and tab 2 having another attachment. Could you please help me to divide them.

Thankyou

**Comment by inoerp** [comment]
All the attachment information are stored in  file_reference, and as per the current design, the files are associated with a single class file. So, system does not distinguish when you attach more than 1file to a document (say purchase order, sales order or an invoice )

The best alternate solution is to create file fields in each document and use a custom template to show them in different positions

**Comment by inoerp** [comment]
Closing this issue log as the features are frozen for the next release. However, we will consider and try to incorporate this feature in the upcoming releases
