### ISSUE TITLE
Hardcoded HTTP

### ISSUE THREAD

**Issue by nysander** [inoerp/inoERP#65]
I am unable to use Inoerp on HTTPS server because there are hardcoded links in non secure HTTP protocol

Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure stylesheet 'http://domain.tld/themes/default/public.css'. This request has been blocked; the content must be served over HTTPS.
(index):11 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure stylesheet 'http://domain.tld/themes/default/menu.css'. This request has been blocked; the content must be served over HTTPS.
(index):12 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure stylesheet 'http://domain.tld/themes/default/jquery.css'. This request has been blocked; the content must be served over HTTPS.
(index):13 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure stylesheet 'http://domain.tld/tparty/bootstrap/css/bootstrap.css'. This request has been blocked; the content must be served over HTTPS.
(index):15 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure stylesheet 'http://domain.tld/tparty/bootstrap/css/style.css'. This request has been blocked; the content must be served over HTTPS.
(index):17 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure stylesheet 'http://domain.tld/tparty/font-awesome/css/font-awesome.min.css'. This request has been blocked; the content must be served over HTTPS.
(index):21 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure stylesheet 'http://domain.tld/themes/default/index.css'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure script 'http://domain.tld/includes/js/jquery-2.0.3.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure script 'http://domain.tld/includes/js/jquery-ui.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure script 'http://domain.tld/tparty/bootstrap/js/bootstrap.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure script 'http://domain.tld/tparty/bootstrap/js/menu.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure script 'http://domain.tld/includes/js/custom/tinymce/tinymce.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure script 'http://domain.tld/includes/js/save.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure script 'http://domain.tld/includes/js/custom_plugins.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure script 'http://domain.tld/includes/js/basics.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure script 'http://domain.tld/includes/js/jssor.slider.mini.js'. This request has been blocked; the content must be served over HTTPS.
(index):77 Mixed Content: The page at 'https://domain.tld/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://domain.tld/extensions/ino_user/user_login.php'. This endpoint should be made available over a secure connection.
(index):123 Mixed Content: The page at 'https://domain.tld/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://domain.tld/extensions/ino_user/user_login.php'. This endpoint should be made available over a secure connection.
(index):199 Mixed Content: The page at 'https://domain.tld/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://domain.tld/extensions/ino_user/user_login.php'. This endpoint should be made available over a secure connection.
(index):259 Mixed Content: The page at 'https://domain.tld/' was loaded over HTTPS, but requested an insecure image 'http://domain.tld/files/logo.png'. This content should also be served over HTTPS.
(index):331 Uncaught ReferenceError: $ is not defined
    at (index):331

**Comment by inoerp** [comment]
inoERP works perfectly fine in https....check the ino_protocol function in functions.inc file and see if your settings satisfy the condition.
The simple workaround is  to return the "https://" protocol from that function

**Comment by nysander** [comment]
above is from today master clone without any changes to code. this should work without intervention inside code

**Comment by inoerp** [comment]
Check your server settings
