### ISSUE TITLE
inoerp payslip header not working

### ISSUE THREAD

**Issue by priyakps** [inoerp/inoERP#67]
in payroll,payslip header is not working.....period name id shows empty dropdown list....

**Comment by inoerp** [comment]
Don't raise an issue if you don't understand any functionalities. Use the forum and create a post.

The period name is visible only if employee name is selected and the employee is associated with a payroll schedule. If you navigate to self-service -> Payslip, the system will show you period names as the employee name defaults from your user login. However, the period name will be blank in Payroll -> Payslip form as that form is used by HR person to select all employees and view/update their payroll.
