### ISSUE TITLE
record inactive

### ISSUE THREAD

**Issue by Sriram1234567** [inoerp/inoERP#68]
In inoerp application when we are deleting any record that was deleting from database .but we need  the data not be deleted, it has to be inactive  and not visible in frontend

**Comment by inoerp** [comment]
If audit trial is required, then data are not deleted from the database else the data is deleted.

Delete means delete not inactive. Where ever inactive feature is required - for master data such as Item, Supplier, Customer, etc. - it's provided as a separate function.
There is no business logic behind keeping all the data when a user wants to delete it.
