### ISSUE TITLE
procedure

### ISSUE THREAD

**Issue by jony1982** [inoerp/inoERP#7]
Hello Nishit,

Thanks For the reply , Can you provide me the steps to follow the above. And also can you provide the stesps to  create the Group and how to assign that group to the organization and then users to that group.

Thank You

**Comment by inoerp** [comment]
Uploaded a doc with screenshots in the [Forum](http://inoideas.org/content.php?mode=2&content_id=273&content_type_id=1)
Closing this tkt. You can ask your questions in the forum.
