### ISSUE TITLE
Multiple vulnerabilities

### ISSUE THREAD

**Issue by fgeek** [inoerp/inoERP#76]
inoERP issues

**Comment by inoerp** [comment]
Stop spamming here. If you have any issue then write it down in details don't put any link to advertise any site

**Comment by fgeek** [comment]
It was not a spam. The link is archive for well known mailing list for security discussion (oss-security) and the link contained three probably unfixed security vulnerabilities. The link does not even seem to have any advertisements. I was just worried about your users security. According to the advisory they have tried to contact inoERP many times:
```
2017-01-25  Issue discovered
2017-01-26  Vendor contacted -> no response
2017-02-20  Vendor contacted again -> no response
2017-03-06  Vendor contacted again -> no response
2017-03-27  Advisory Release
```

**Comment by inoerp** [comment]
No worries. We will work on them.

**Comment by inoerp** [comment]
All these issues have been resolved and committed
