### ISSUE TITLE
can't install inoerp

### ISSUE THREAD

**Issue by bilalbayasut** [inoerp/inoERP#8]
why do i can't install inoerp whether using github or directly download in zip.. 
the error is :

Parse error: syntax error, unexpected '$object' (T_VARIABLE) in C:\xampp\htdocs\inoerp\includes\general_class\trait_dbObject_t.inc on line 1110

**Comment by inoerp** [comment]
make sure you have PHP 5.5 +
PHP 5.5+
MySQL Server version: 5.6.17+
