### ISSUE TITLE
Inoerp 

### ISSUE THREAD

**Issue by Deva4** [inoerp/inoERP#9]
Hello,
I need to know the flow of inoerp could you provide me the documentation

**Comment by inoerp** [comment]
Please check the site inoideas.org and also you tube.
If you are familiar with APICS BOK processes or have worked with 11i/R12/Peoplesoft then you can easily understand...else learning curve can be tough

**Comment by Deva4** [comment]
Hello ,

**Comment by Deva4** [comment]
Hello 
i don't know about APICS BOK or 11i/R12 peoplesoft could you describe in detail how it work  
is their any flow and document
